### ISSUE TITLE
elrond-rosetta-observer-mainnet container exits right away

### ISSUE THREAD

**Issue by Palak3196** [multiversx/mx-chain-rosetta-docker#21]
Hi Team,

We tried to setup the rosetta-docker for elrond following the document given in this repository.

After cloning the repository in our ubuntu server, we were able to successfully build the image with docker.

However, as soon as we create the 1+1+1 containers for mainnet using: `docker compose --file ./docker-compose-mainnet.yml --env-file ./mainnet.env --project-name elrond-mainnet up --detach`,
the observer container exits right away with below logs:

```
Network: mainnet
INFO [2022-11-08 09:58:35.244]   generating files in                      folder = /elrond
Created observer key.
Created symlink to config folder.
Make sure the directory /data/db exists and contains a (recent) blockchain archive.
```

Is there any prerequisite that we're missing?

Thanks,
Palak

**Comment by andreibancioiu** [comment]
Hello @Palak3196, and thank you for your interest into using the Rosetta setup!

Bits of documentation regarding database initialization are located here: https://github.com/ElrondNetwork/rosetta#download-archives. If the database isn't initialized, the container stops, as you've described.

Example of how the database should look like:

```
./db/
└── D
 ...
    ├── Epoch_2526
    ├── Epoch_2527
    ├── Epoch_2528
...
    ├── Epoch_2676
    ├── Epoch_2677
    ├── Epoch_2678
    ├── Epoch_2679
    ├── Epoch_2680
    ├── Epoch_2681
 ...
    └── Static
```
What _network_ (devnet, mainnet) and _shard_ are you interested into querying via Rosetta?

**Comment by Palak3196** [comment]
Thanks for reaching out so quick, Andrei.

We're interested in mainnet, complete historical data startign from first block itself, till latest block. 
I've requested for the historical archive on the telegram channel. Is there anythig else I need to know?

Thanks,
Palak

**Comment by Palak3196** [comment]
So I downloaded this tar https://elrond-mainnet-db-archive.s3.eu-central-1.amazonaws.com/full-history-do-public/08-Nov-2022/Full-History-DB-Shard-metachain.tar.gz.

I did untar to "../rosetta-docker/data/db" folder in my VM.

Now under folder "db" I can see a folder named as "1", which further contains the Epochs as you have shown.
Is it how its supposed to be? Or the Epochs should skip the 1 folder and sit in the db directly?

**Comment by andreibancioiu** [comment]
Hello @Palak3196, 

Do you think you can describe a bit your use-case?

Our Rosetta implementation is tested to work with & correctly handle the mainnet data **after epoch ~700**, while older data isn't supported (the Data API may work for older data, but correctly formatting the balance-changing operations is not guaranteed / not tested, and will not be supported).

Furthermore, you seem to have downloaded a metachain archive. Perhaps you are interested into observing a shard, instead? If so, which one? Also, you may be interested into supporting historical lookup queries - is this the case? Then, a different set of databases should be downloaded, from a different location, using the bash snippets described at: https://github.com/ElrondNetwork/rosetta#download-archives. We'll discuss a bit internally if we should post the public link of the archive here, or not.

For mainnet, the folder structure would be something like:

```
./db/
└── 1
 ...
    ├── Epoch_799
    ├── Epoch_800
 ...
    └── Static
```

**Comment by Palak3196** [comment]
Hello Andrei,

Our use case is to stand up an EGLD observer node (since we don't want to take part in staking), preferably a rosetta-docker, to eventually query block data (like transactions, hashes) using rpc or http endpoints.

We're not limited to a particular shard or any epoch limited. But interested in each block's data starting from the first block till the latest.

Would you have a snapshot available for my use case?

I see https://github.com/ElrondNetwork/rosetta#download-archives. just leads me to the telegram channel, from where your devs gave me the metachain snapshot mentioned above.

**Comment by Palak3196** [comment]
Actually we'd really prefer a rosetta docker node so that we can use the rosetta API's that use port 8080
Like I said, we need entire historical data and not specific shards

**Comment by Palak3196** [comment]
@andreibancioiu would you mind connecting with us over a Zoom call? Would really appreciate your help on resolving all our queries at once- we won't take much of your time. Thank you

**Comment by andreibancioiu** [comment]
Issue can be closed now.

Discussed separately over telegram about the download of archives.

Additionally, since [v0.4.0](https://github.com/multiversx/mx-chain-rosetta-docker/releases/tag/v0.4.0), the setup flow includes a download step (guided by a series of environment variables).
